language: node_js
node_js:
  - "10"

env:
  global:
    - NODE_ENV=production

# safelist
branches:
  only:
  - master

# do ./scripts folder executable
before_install:
  - chmod +x ./scripts/*

script:
  - yarn clearout
  - yarn install
  - yarn custom-audit
  - yarn test
  - yarn build