language: node_js
node_js:
  - "10"

env:
  global:
    - NODE_ENV=production

cache:
  yarn: true
  directories:
    - node_modules

# safelist
branches:
  only:
  - master

script:
  - yarn clearout
  - yarn install
  - yarn custom-audit
  - yarn test
  - yarn build