language: node_js
node_js:
  - "10"

env:
  global:
    - NODE_ENV=production

# do ./scripts folder executable
before_install:
  - pip install --user codecov
  - chmod +x ./scripts/*

after_success:
  - codecov --file coverage/lcov.info --disable search

script:
  - yarn clearout
  - yarn install
  - yarn test && node_modules/.bin/codecov -t 4ac5e4e0-a8fd-4b74-98b8-a0b64364a264
  - yarn build