language: node_js
node_js:
  - "10"

env:
  global:
    - NODE_ENV=production

# do ./scripts folder executable
before_install:
  - pip install --user codecov
  - chmod +x ./scripts/*

after_success:
  - codecov

script:
  - yarn clearout
  - yarn install
  - yarn test
  - yarn cypress-run
  - yarn build